services:
  - type: web
    name: bookstore-php-app     # اسم الخدمة (تقدر تغيره)
    env: php
    plan: free
    rootDir: .
    buildCommand: ""            # مش محتاج بناء
    startCommand: ""            # Render تلقائياً يشغل PHP
